config/routes.rb
CakeMyDaySite::Application.routes.draw do

  match "store"                       => "store#index",                 :as => :store
  match "store/design_my_cake"        => "store#design_my_cake",        :as => :design_my_cake
  match "store/edit_my_cake"          => "store#edit_my_cake",          :as => :edit_my_cake
  match "store/add_this_to_the_cart"  => "store#add_this_to_the_cart",  :as => :add_this_to_the_cart, :method => :post
  match "store/update_cake_design"    => "store#update_cake_design",    :as => :update_cake_design, :method => :post
  match "store/delete_cart"           => "store#delete_cart",           :as => :delete_cart
  match "store/delete_cake"           => "store#delete_cake",           :as => :delete_cake
  match "store/update_cake_details"   => "store#update_cake_details",   :as => :update_cake_details
  match "store/show_cake"             => "store#show_cake",             :as => :show_cake
  match "store/show_cart"             => "store#show_cart",             :as => :show_cart
  match "store/start_checkout"        => "store#start_checkout",        :as => :start_checkout
  match "store/checkout_registration" => "store#checkout_registration", :as => :checkout_registration
  match "store/checkout_process"      => "store#checkout_process",      :as => :checkout_process
  match "store/buy_now"               => "store#buy_now",               :as => :buy_now
  match "store/checkout_complete"     => "store#checkout_complete",     :as => :checkout_complete
  match "store/:product_name"         => "store#show",                  :as => :store_product
  match 'search'                      => 'store#search',                :as => :search, :method => :post
  
  match 'login'    => "user_sessions#new",     :as => :login
  match 'log_in'   => "user_sessions#new",     :as => :log_in
  match 'signin'   => "user_sessions#new",     :as => :signin
  match 'sign_in'  => "user_sessions#new",     :as => :sign_in
  match 'logout'   => "user_sessions#destroy", :as => :logout
  match 'account'  => 'users#show',            :as => :account
  match 'my_account'  => 'users#show',         :as => :my_account
  match 'signup'   => 'users#new',             :as => :signup
  match 'sign_up'  => 'users#new',             :as => :sign_up
  match 'register' => 'users#new',             :as => :register
  match 'change_password' => 'users#change_password', :as => :change_password
  
  match 'link_finished_product_image' => 'finished_products#link_image', :as => :link_finished_product_image
  match 'link_product_image' => 'products#link_image', :as => :link_product_image
  match 'new_finished_product_ingredient' => 'finished_products#new_finished_product_ingredient', :as => :new_finished_product_ingredient
  match 'edit_finished_product_ingredient' => 'finished_products#edit_finished_product_ingredient', :as => :edit_finished_product_ingredient
  match 'create_finished_product_ingredient' => 'finished_products#create_finished_product_ingredient', :as => :create_finished_product_ingredient
  match 'update_finished_product_ingredient' => 'finished_products#update_finished_product_ingredient', :as => :update_finished_product_ingredient
  match 'finished_product_ingredient_destroy' => 'finished_products#finished_product_ingredient_destroy', :as => :finished_product_ingredient_destroy
  
  resources :cakes
  resources :currencies
  resources :customers
  resources :finished_products
  resources :general_settings
  resources :images
  resources :options_lists
  resources :pay_pal_statuses
  resources :pay_pal_transactions
  resources :products #do
  resources :product_categories
  resources :product_images
  resources :product_prices
  resources :production_quota
  resources :shopping_carts
  resources :shopping_cart_items
  resources :shopping_cart_statuses
  resources :special_occasions
  resources :static_pages
  resources :users
  resources :user_groups
  resources :user_sessions

  root :to => 'store#index'

  
  match '/:page', :controller => :static_pages, :action => :display
  
end

app/models/options_list.rb
# OptionsList.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class OptionsList < ActiveRecord::Base
  attr_accessible :name, :options, :visible_label
  
  has_many :product_categories
  has_many :products

  validates_presence_of :name, :options, :visible_label
  validates_uniqueness_of :name

end

app/controllers/options_lists_controller.rb
# OptionsController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class OptionsListsController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  
  def index
    # GET /options_lists
    # GET /options_lists.json
    @options_lists = OptionsList.all(order: 'name')

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @options_lists }
    end
  end

  def show
    # GET /options_lists/1
    # GET /options_lists/1.json
    @options_list = OptionsList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @options_list }
    end
  end

  def new
    # GET /options_lists/new
    # GET /options_lists/new.json
    @options_list = OptionsList.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @options_list }
    end
  end

  def edit
    # GET /options_lists/1/edit
    @options_list = OptionsList.find(params[:id])
  end

  def create
    # POST /options_lists
    # POST /options_lists.json
    @options_list = OptionsList.new(params[:options_list])

    respond_to do |format|
      if @options_list.save
        format.html { redirect_to @options_list, notice: 'Options list was successfully created.' }
        #format.json { render json: @options_list, status: :created, location: @options_list }
      else
        format.html { render action: "new" }
        #format.json { render json: @options_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /options_lists/1
    # PUT /options_lists/1.json
    @options_list = OptionsList.find(params[:id])

    respond_to do |format|
      if @options_list.update_attributes(params[:options_list])
        format.html { redirect_to @options_list, notice: 'Options list was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @options_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /options_lists/1
    # DELETE /options_lists/1.json
    @options_list = OptionsList.find(params[:id])
    @options_list.destroy

    respond_to do |format|
      format.html { redirect_to options_lists_url }
      #format.json { head :no_content }
    end
  end

end

app/helpers/options_lists_helper.rb
module OptionsListsHelper
end

app/views/options_lists/_form.html.erb
<%= form_for(@options_list) do |f| %>
  <% if @options_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@options_list.errors.count, "error") %> prohibited this options_list from being saved:</h2>

      <ul>
      <% @options_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="form-label"><%= f.label :name %></span>
    <span class="form-field"><%= f.text_field :name %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :visible_label %></span>
    <span class="form-field"><%= f.text_field :visible_label %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :options %></span>
    <span class="form-field"><%= f.text_area :options, :size => "50x5" %></span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options_lists/edit.html.erb
<h1>Edit Options List</h1>

<%= render 'form' %>

<%= link_to 'View', @options_list %> |
<%= link_to 'Back', options_lists_path %>

app/views/options_lists/index.html.erb
<h1>Options Lists</h1>
<table>
  <tr>
    <th style="width: 100px;">Name</th>
    <th style="width: 200px;">Visible label</th>
    <th style="width: 200px;">Options</th>
    <td style="width:  80px;"></td>
    <td style="width:  60px;"></td>
  </tr>
  <% @options_lists.each do |options_list| %>
    <tr style="background-color: <%= cycle("#f9d4e4","white") %>;" class="graduated-background">
      <td><%= options_list.name %></td>
      <td><%= options_list.visible_label %></td>
      <td><%= sanitize options_list.options.gsub(", ","<br/>") %></td>
      <td><%= link_to 'View', options_list %> | 
          <%= link_to 'Edit', edit_options_list_path(options_list) %></td>
      <%- if options_list.products.count == 0 %>
        <%= render :partial => '/layouts/delete_button', :locals => {:label => "options list", :item => options_list} -%>
      <%- else -%>
        <td><%= options_list.products.count %> items</td>
      <%- end -%>
    </td>
  <% end %>
</table><br/>
<%= link_to 'New', new_options_list_path %>

app/views/options_lists/new.html.erb
<h1>New Options List</h1>

<%= render 'form' %>

<%= link_to 'Back', options_lists_path %>

app/views/options_lists/show.html.erb
<h1>Options List #<%= params[:id] %></h1>
<table>
  <tr><td>Name:</td><td><%= @options_list.name %></td></tr>
  <tr><td>Visible label:</td><td><%= @options_list.visible_label %></td></tr>
  <tr><td>Options:</td><td><%= sanitize @options_list.options.gsub(", ","<br/>") %></td></tr>
  <tr><td colspan=2><h2>Products</h2></td></tr>
  <tr><td>&nbsp;</td><td>
    <% @options_list.products.each do |p| -%>
      <%= link_to(p.name, product_url(:id => p.id), :title => "click to view product") %><br/>
    <% end %>
    </td>
  </td>
</table><br/>
<%= link_to 'Back', options_lists_path %> | <%= link_to 'Edit', edit_options_list_path(@options_list) %>