config/routes.rb
CakeMyDaySite::Application.routes.draw do

  match "store"                       => "store#index",                 :as => :store
  match "store/design_my_cake"        => "store#design_my_cake",        :as => :design_my_cake
  match "store/edit_my_cake"          => "store#edit_my_cake",          :as => :edit_my_cake
  match "store/add_this_to_the_cart"  => "store#add_this_to_the_cart",  :as => :add_this_to_the_cart, :method => :post
  match "store/update_cake_design"    => "store#update_cake_design",    :as => :update_cake_design, :method => :post
  match "store/delete_cart"           => "store#delete_cart",           :as => :delete_cart
  match "store/delete_cake"           => "store#delete_cake",           :as => :delete_cake
  match "store/update_cake_details"   => "store#update_cake_details",   :as => :update_cake_details
  match "store/show_cake"             => "store#show_cake",             :as => :show_cake
  match "store/show_cart"             => "store#show_cart",             :as => :show_cart
  match "store/start_checkout"        => "store#start_checkout",        :as => :start_checkout
  match "store/checkout_registration" => "store#checkout_registration", :as => :checkout_registration
  match "store/checkout_process"      => "store#checkout_process",      :as => :checkout_process
  match "store/buy_now"               => "store#buy_now",               :as => :buy_now
  match "store/checkout_complete"     => "store#checkout_complete",     :as => :checkout_complete
  match "store/:product_name"         => "store#show",                  :as => :store_product
  match 'search'                      => 'store#search',                :as => :search, :method => :post
  
  match 'login'    => "user_sessions#new",     :as => :login
  match 'log_in'   => "user_sessions#new",     :as => :log_in
  match 'signin'   => "user_sessions#new",     :as => :signin
  match 'sign_in'  => "user_sessions#new",     :as => :sign_in
  match 'logout'   => "user_sessions#destroy", :as => :logout
  match 'account'  => 'users#show',            :as => :account
  match 'my_account'  => 'users#show',         :as => :my_account
  match 'signup'   => 'users#new',             :as => :signup
  match 'sign_up'  => 'users#new',             :as => :sign_up
  match 'register' => 'users#new',             :as => :register
  match 'change_password' => 'users#change_password', :as => :change_password
  
  match 'link_finished_product_image' => 'finished_products#link_image', :as => :link_finished_product_image
  match 'link_product_image' => 'products#link_image', :as => :link_product_image
  match 'new_finished_product_ingredient' => 'finished_products#new_finished_product_ingredient', :as => :new_finished_product_ingredient
  match 'edit_finished_product_ingredient' => 'finished_products#edit_finished_product_ingredient', :as => :edit_finished_product_ingredient
  match 'create_finished_product_ingredient' => 'finished_products#create_finished_product_ingredient', :as => :create_finished_product_ingredient
  match 'update_finished_product_ingredient' => 'finished_products#update_finished_product_ingredient', :as => :update_finished_product_ingredient
  match 'finished_product_ingredient_destroy' => 'finished_products#finished_product_ingredient_destroy', :as => :finished_product_ingredient_destroy
  
  resources :cakes
  resources :currencies
  resources :customers
  resources :finished_products
  resources :general_settings
  resources :images
  resources :options_lists
  resources :pay_pal_statuses
  resources :pay_pal_transactions
  resources :products #do
  resources :product_categories
  resources :product_images
  resources :product_prices
  resources :production_quota
  resources :shopping_carts
  resources :shopping_cart_items
  resources :shopping_cart_statuses
  resources :special_occasions
  resources :static_pages
  resources :users
  resources :user_groups
  resources :user_sessions

  root :to => 'store#index'

  
  match '/:page', :controller => :static_pages, :action => :display
  
end

app/models/shopping_cart.rb
# ShoppingCart.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ShoppingCart < ActiveRecord::Base
  attr_accessible :customer_id, :pay_pal_status_id, :shopping_cart_status_id

  has_many    :cakes
  belongs_to  :customer
  belongs_to  :pay_pal_status
  has_many    :pay_pal_transactions, :order => :created_at
  has_many    :cakes, :order => :created_at
  belongs_to  :shopping_cart_status
  belongs_to  :creator,
              :class_name => "User",
              :foreign_key => "created_by"
  belongs_to  :updater,
              :class_name => "User",
              :foreign_key => "updated_by"
  
  validates_numericality_of :shopping_cart_status_id
  validates_numericality_of :customer_id, :allow_nil => true
  validates_numericality_of :pay_pal_status_id
  
  def total_value
    total = 0.0
    cakes.each do |c|
      total += c.shopping_cart_items.sum(:line_total)
    end
    return total
  end
  
end

app/controllers/shopping_carts_controller.rb
# ShoppingCartsController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ShoppingCartsController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  before_filter :get_variables
  
  def index
    # GET /shopping_carts
    # GET /shopping_carts.json
    @shopping_carts = ShoppingCart.all(order: "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @shopping_carts }
    end
  end

  def show
    # GET /shopping_carts/1
    # GET /shopping_carts/1.json
    @shopping_cart = ShoppingCart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @shopping_cart }
    end
  end

  def new
    # GET /shopping_carts/new
    # GET /shopping_carts/new.json
    @shopping_cart = ShoppingCart.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @shopping_cart }
    end
  end

  def edit
    # GET /shopping_carts/1/edit
    @shopping_cart = ShoppingCart.find(params[:id])
  end

  def create
    # POST /shopping_carts
    # POST /shopping_carts.json
    @shopping_cart = ShoppingCart.new(params[:shopping_cart])

    respond_to do |format|
      if @shopping_cart.save
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully created.' }
        #format.json { render json: @shopping_cart, status: :created, location: @shopping_cart }
      else
        format.html { render action: "new" }
        #format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /shopping_carts/1
    # PUT /shopping_carts/1.json
    @shopping_cart = ShoppingCart.find(params[:id])

    respond_to do |format|
      if @shopping_cart.update_attributes(params[:shopping_cart])
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /shopping_carts/1
    # DELETE /shopping_carts/1.json
    @shopping_cart = ShoppingCart.find(params[:id])
    @shopping_cart.destroy

    respond_to do |format|
      format.html { redirect_to shopping_carts_url }
      #format.json { head :no_content }
    end
  end

  private
  
  def get_variables
    @shopping_cart_statuses = ShoppingCartStatus.all(:order => "running_order")
    @pay_pal_statuses = PayPalStatus.all
  end

end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_form.html.erb
<%= form_for(@shopping_cart) do |f| %>
  <% if @shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
      <% @shopping_cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="form-label"><%= f.label :shopping_cart_status_id %></span>
    <span class="form-field"><%= f.collection_select :shopping_cart_status_id, @shopping_cart_statuses, :id, :name %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :pay_pal_status_id %></span>
    <span class="form-field"><%= f.collection_select :pay_pal_status_id, @pay_pal_statuses, :id, :name %></span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<h1>Edit Shopping Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_carts_path %> | 
<%= link_to 'View', @shopping_cart %>

app/views/shopping_carts/index.html.erb
<h1>Shopping Carts</h1>
<table>
  <tr>
    <th style="width:  30px;">ID</th>
    <th style="width: 200px;">Customer</th>
    <th style="width: 150px;">Email</th>
    <th style="width: 100px;">Phone</th>
    <th style="width: 100px;">Shopping cart status</th>
    <th style="width:  70px;">PayPal</th>
    <td style="width:  90px;"></td>
  </tr>
  <% @shopping_carts.each do |shopping_cart| %>
    <tr style="background-color: <%= cycle("#f9d4e4","inherit") %>;" class="graduated-background">
      <td><%= shopping_cart.id %></td>
      <% if shopping_cart.customer and shopping_cart.customer.user %>
      <td><%= link_to(shopping_cart.customer.user.full_name, customer_url(shopping_cart.customer_id), :title => "click to view customer") %></td>
      <td><%= link_to(shopping_cart.customer.user.login, "mailto:" + shopping_cart.customer.user.login, :title => "click to send email") %></td>
      <td><%= shopping_cart.customer.contact_phone_number %></td>
      <% else %>
      <td>--</td><td>--</td><td>--</td>
      <% end %>
      <td><%= shopping_cart.shopping_cart_status.name %></td>
      <% if shopping_cart.pay_pal_status_id.to_i > 0 %>
      <td><%= shopping_cart.pay_pal_status.name %></td>
      <% else %>
      <td>--</td>
      <% end %>
      <td><%= link_to 'View', shopping_cart %>
          <%= link_to 'Edit', edit_shopping_cart_path(shopping_cart) %></td>
    </td>
  <% end %>
</table><br/>

<p>Add new Shopping Carts through the online store.</p>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<h1>Shopping Cart #<%= params[:id] %></h1>
<table>
  <tr><td>Customer:</td><td>
    <% if @shopping_cart.customer and @shopping_cart.customer.user %>
      <%= link_to(@shopping_cart.customer.user.full_name, customer_url(@shopping_cart.customer_id), :title => "click to view the customer's details") %><br/>
      <%= link_to(sanitize(@shopping_cart.customer.user.login), "mailto:" + @shopping_cart.customer.user.login) %>
    <% else %>
    --
    <% end %>
    </td></tr>
  <tr><td>Shopping cart status:</td><td><%= @shopping_cart.shopping_cart_status.name %></td></tr>
  <tr><td>PayPal status:</td><td>
    <% if @shopping_cart.pay_pal_status_id.to_i > 0 %>
    <%= @shopping_cart.pay_pal_status.name %>
    <% else %>
    --
    <% end %>
  </td></tr>
</table><br/>

<h2>Cakes</h2>
<table>
  <tr>
    <th>Product name</th>
    <th>Customer description</th>
    <th>Options</th>
    <th style="text-align:right;">Unit Price</th>
    <th style="text-align:right;">Quantity</th>
    <th style="text-align:right;">Line Total</th>
  </tr>
  
  <% @shopping_cart.cakes.each do |cake| %>
    <tr><td colspan=4><h2>Cake #<%= cake.id %></h2></td></tr>
    <tr class="graduated-background"><td>Required at:</td><td colspan=5><%= cake.cake_required_at %></td></tr>
    <tr class="graduated-background"><td>Special occasion:</td><td colspan=5><%= cake.special_occasion %></td></tr>
    <tr class="graduated-background"><td>Name to appear on cake:</td><td colspan=5><%= cake.name_to_appear_on_cake %></td></tr>
    <tr class="graduated-background"><td>Customer's description:</td><td colspan=5><%= cake.general_description_from_customer %></td></tr>
    <tr class="graduated-background"><td>Confectioner's notes:</td><td colspan=5><%= cake.confectioners_notes %></td></tr>
    <% if cake.based_on_finished_product_id.to_i > 0 %>
      <tr class="graduated-background"><td>Based on:</td><td colspan=5><%= cake.based_on_finished_product_id %></td></tr>
    <% end %>
    <tr class="graduated-background"><td>This week's workload:</td><td colspan=5><%= link_to(cake.production_quotum.bookings, cake.production_quotum, :title => "click to see the week's bookings") %></td></tr>
    <tr><td>&nbsp;</td></tr>
    <% cake.shopping_cart_items.each do |item| %>
      <tr class="graduated-background">
        <td><%= link_to(item.product.name, product_url(item.product_id), :title => "click to view product") %></td>
        <td><%= item.user_description %></td>
        <td><%= item.product_options_list_choice %><br/>
            <%= item.global_options_list_choice %>
        </td>
        <td style="text-align:right;"><%= sanitize(number_to_currency(item.unit_price, :unit => @general_setting.ccy, :precision => 2)) %></td>
        <td style="text-align:right;"><%= item.quantity %></td>
        <td style="text-align:right;"><%= sanitize(number_to_currency(item.line_total, :unit => @general_setting.ccy, :precision => 2)) %></td>
      </tr>
    <% end %>
    <tr class="graduated-background">
      <td colspan=5>GRAND TOTAL FOR THIS CAKE:</td>
      <td style="text-align:right;border-top: 1px solid black;border-bottom: 3px double black;">
      <%= sanitize(number_to_currency(cake.total_value, :unit => @general_setting.ccy, :precision => 2)) %></td>
    </tr>
  <% end %>
</table><br/>
<%= link_to 'Back', shopping_carts_path %> | <%= link_to 'Edit', edit_shopping_cart_path(@shopping_cart) %>