config/routes.rb
CakeMyDaySite::Application.routes.draw do

  match "store"                       => "store#index",                 :as => :store
  match "store/design_my_cake"        => "store#design_my_cake",        :as => :design_my_cake
  match "store/edit_my_cake"          => "store#edit_my_cake",          :as => :edit_my_cake
  match "store/add_this_to_the_cart"  => "store#add_this_to_the_cart",  :as => :add_this_to_the_cart, :method => :post
  match "store/update_cake_design"    => "store#update_cake_design",    :as => :update_cake_design, :method => :post
  match "store/delete_cart"           => "store#delete_cart",           :as => :delete_cart
  match "store/delete_cake"           => "store#delete_cake",           :as => :delete_cake
  match "store/update_cake_details"   => "store#update_cake_details",   :as => :update_cake_details
  match "store/show_cake"             => "store#show_cake",             :as => :show_cake
  match "store/show_cart"             => "store#show_cart",             :as => :show_cart
  match "store/start_checkout"        => "store#start_checkout",        :as => :start_checkout
  match "store/checkout_registration" => "store#checkout_registration", :as => :checkout_registration
  match "store/checkout_process"      => "store#checkout_process",      :as => :checkout_process
  match "store/buy_now"               => "store#buy_now",               :as => :buy_now
  match "store/checkout_complete"     => "store#checkout_complete",     :as => :checkout_complete
  match "store/:product_name"         => "store#show",                  :as => :store_product
  match 'search'                      => 'store#search',                :as => :search, :method => :post
  
  match 'login'    => "user_sessions#new",     :as => :login
  match 'log_in'   => "user_sessions#new",     :as => :log_in
  match 'signin'   => "user_sessions#new",     :as => :signin
  match 'sign_in'  => "user_sessions#new",     :as => :sign_in
  match 'logout'   => "user_sessions#destroy", :as => :logout
  match 'account'  => 'users#show',            :as => :account
  match 'my_account'  => 'users#show',         :as => :my_account
  match 'signup'   => 'users#new',             :as => :signup
  match 'sign_up'  => 'users#new',             :as => :sign_up
  match 'register' => 'users#new',             :as => :register
  match 'change_password' => 'users#change_password', :as => :change_password
  
  match 'link_finished_product_image' => 'finished_products#link_image', :as => :link_finished_product_image
  match 'link_product_image' => 'products#link_image', :as => :link_product_image
  match 'new_finished_product_ingredient' => 'finished_products#new_finished_product_ingredient', :as => :new_finished_product_ingredient
  match 'edit_finished_product_ingredient' => 'finished_products#edit_finished_product_ingredient', :as => :edit_finished_product_ingredient
  match 'create_finished_product_ingredient' => 'finished_products#create_finished_product_ingredient', :as => :create_finished_product_ingredient
  match 'update_finished_product_ingredient' => 'finished_products#update_finished_product_ingredient', :as => :update_finished_product_ingredient
  match 'finished_product_ingredient_destroy' => 'finished_products#finished_product_ingredient_destroy', :as => :finished_product_ingredient_destroy
  
  resources :cakes
  resources :currencies
  resources :customers
  resources :finished_products
  resources :general_settings
  resources :images
  resources :options_lists
  resources :pay_pal_statuses
  resources :pay_pal_transactions
  resources :products #do
  resources :product_categories
  resources :product_images
  resources :product_prices
  resources :production_quota
  resources :shopping_carts
  resources :shopping_cart_items
  resources :shopping_cart_statuses
  resources :special_occasions
  resources :static_pages
  resources :users
  resources :user_groups
  resources :user_sessions

  root :to => 'store#index'

  
  match '/:page', :controller => :static_pages, :action => :display
  
end

app/models/user_group.rb
# UserGroup.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class UserGroup < ActiveRecord::Base
  attr_accessible :description, :is_a_manager, :is_an_admin, :name
  
  has_many :users
  
  validates_presence_of :description, :name
  validates_uniqueness_of :name
  
end

app/controllers/user_groups_controller.rb
# UserGroupsController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class UserGroupsController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  before_filter :admin_required, :except => [:index, :show]

  def index
    # GET /user_groups
    # GET /user_groups.json
    @user_groups = UserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @user_groups }
    end
  end

  def show
    # GET /user_groups/1
    # GET /user_groups/1.json
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @user_group }
    end
  end

  def new
    # GET /user_groups/new
    # GET /user_groups/new.json
    @user_group = UserGroup.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @user_group }
    end
  end

  def edit
    # GET /user_groups/1/edit
    @user_group = UserGroup.find(params[:id])
  end

  def create
    # POST /user_groups
    # POST /user_groups.json
    @user_group = UserGroup.new(params[:user_group])

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        #format.json { render json: @user_group, status: :created, location: @user_group }
      else
        format.html { render action: "new" }
        #format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /user_groups/1
    # PUT /user_groups/1.json
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      if @user_group.update_attributes(params[:user_group])
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /user_groups/1
    # DELETE /user_groups/1.json
    @user_group = UserGroup.find(params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url }
      #format.json { head :no_content }
    end
  end

end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :is_a_manager %><br />
    <%= f.check_box :is_a_manager %>
  </div>
  <div class="field">
    <%= f.label :is_an_admin %><br />
    <%= f.check_box :is_an_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Edit user_group</h1>

<%= render 'form' %>

<%= link_to 'View', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<h1>User Groups</h1>
<table>
  <tr>
    <th style="width: 100px;">Name</th>
    <th style="width: 100px;">Description</th>
    <th style="width: 100px;">Is a manager</th>
    <th style="width: 100px;">Is an admin</th>
    <th style="width:  40px;"></th>
    <th style="width:  40px;"></th>
    <th style="width:  40px;"></th>
  </tr>
  <% @user_groups.each do |user_group| %>
    <tr style="background-color: <%= cycle("inherit","inherit") %>;" class="graduated-background">
      <td><%= user_group.name %></td>
      <td><%= user_group.description %></td>
      <td><%= sanitize tick_or_cross user_group.is_a_manager %></td>
      <td><%= sanitize tick_or_cross user_group.is_an_admin %></td>
      <td><%= link_to 'View', user_group %></td>
      <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
      <% if user_group.users.count == 0 %>
      <%= render :partial => '/layouts/delete_button', :locals => {:label => "User Group", :item => user_group} -%>
      <% else %>
      <td><%= user_group.users.count %> users</td>
      <% end %>
    </td>
  <% end %>
</table><br/>
<%= link_to 'New', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New user_group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<h1>User Group #<%= params[:id] %></h1>
<table>
  <tr><td>Name:</td><td><%= @user_group.name %></td></tr>
  <tr><td>Description:</td><td><%= @user_group.description %></td></tr>
  <tr><td>Is a manager:</td><td><%= sanitize tick_or_cross @user_group.is_a_manager %></td></tr>
  <tr><td>Is an admin:</td><td><%= sanitize tick_or_cross @user_group.is_an_admin %></td></tr>
  <tr><td colspan=2><h2>Users</h2></td></tr>
  <tr><td>&nbsp;</td><td>
    <% @user_group.users.each do |u| %>
      <%= link_to(u.login, user_url(:id => u.id), :title => "click to view user") %><br/>
    <% end %>
    </td>
  </tr>
</table><br/>
<%= link_to 'Back', user_groups_path %> | <%= link_to 'Edit', edit_user_group_path(@user_group) %> |