config/routes.rb
CakeMyDaySite::Application.routes.draw do

  match "store"                       => "store#index",                 :as => :store
  match "store/design_my_cake"        => "store#design_my_cake",        :as => :design_my_cake
  match "store/edit_my_cake"          => "store#edit_my_cake",          :as => :edit_my_cake
  match "store/add_this_to_the_cart"  => "store#add_this_to_the_cart",  :as => :add_this_to_the_cart, :method => :post
  match "store/update_cake_design"    => "store#update_cake_design",    :as => :update_cake_design, :method => :post
  match "store/delete_cart"           => "store#delete_cart",           :as => :delete_cart
  match "store/delete_cake"           => "store#delete_cake",           :as => :delete_cake
  match "store/update_cake_details"   => "store#update_cake_details",   :as => :update_cake_details
  match "store/show_cake"             => "store#show_cake",             :as => :show_cake
  match "store/show_cart"             => "store#show_cart",             :as => :show_cart
  match "store/start_checkout"        => "store#start_checkout",        :as => :start_checkout
  match "store/checkout_registration" => "store#checkout_registration", :as => :checkout_registration
  match "store/checkout_process"      => "store#checkout_process",      :as => :checkout_process
  match "store/buy_now"               => "store#buy_now",               :as => :buy_now
  match "store/checkout_complete"     => "store#checkout_complete",     :as => :checkout_complete
  match "store/:product_name"         => "store#show",                  :as => :store_product
  match 'search'                      => 'store#search',                :as => :search, :method => :post
  
  match 'login'    => "user_sessions#new",     :as => :login
  match 'log_in'   => "user_sessions#new",     :as => :log_in
  match 'signin'   => "user_sessions#new",     :as => :signin
  match 'sign_in'  => "user_sessions#new",     :as => :sign_in
  match 'logout'   => "user_sessions#destroy", :as => :logout
  match 'account'  => 'users#show',            :as => :account
  match 'my_account'  => 'users#show',         :as => :my_account
  match 'signup'   => 'users#new',             :as => :signup
  match 'sign_up'  => 'users#new',             :as => :sign_up
  match 'register' => 'users#new',             :as => :register
  match 'change_password' => 'users#change_password', :as => :change_password
  
  match 'link_finished_product_image' => 'finished_products#link_image', :as => :link_finished_product_image
  match 'link_product_image' => 'products#link_image', :as => :link_product_image
  match 'new_finished_product_ingredient' => 'finished_products#new_finished_product_ingredient', :as => :new_finished_product_ingredient
  match 'edit_finished_product_ingredient' => 'finished_products#edit_finished_product_ingredient', :as => :edit_finished_product_ingredient
  match 'create_finished_product_ingredient' => 'finished_products#create_finished_product_ingredient', :as => :create_finished_product_ingredient
  match 'update_finished_product_ingredient' => 'finished_products#update_finished_product_ingredient', :as => :update_finished_product_ingredient
  match 'finished_product_ingredient_destroy' => 'finished_products#finished_product_ingredient_destroy', :as => :finished_product_ingredient_destroy
  
  resources :cakes
  resources :currencies
  resources :customers
  resources :finished_products
  resources :general_settings
  resources :images
  resources :options_lists
  resources :pay_pal_statuses
  resources :pay_pal_transactions
  resources :products #do
  resources :product_categories
  resources :product_images
  resources :product_prices
  resources :production_quota
  resources :shopping_carts
  resources :shopping_cart_items
  resources :shopping_cart_statuses
  resources :special_occasions
  resources :static_pages
  resources :users
  resources :user_groups
  resources :user_sessions

  root :to => 'store#index'

  
  match '/:page', :controller => :static_pages, :action => :display
  
end

app/models/currency.rb
# Currency.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class Currency < ActiveRecord::Base
  attr_accessible :active, :currency_symbol, :full_name, :iso_code, :running_order
  
  has_many :pay_pal_transactions
  has_many :product_prices
  has_one  :general_setting,
           :class_name => "GeneralSetting",
           :foreign_key => "default_currency_id"
  
  validates_presence_of :currency_symbol, :full_name, :iso_code, :running_order
  validates_uniqueness_of :iso_code
  validates_uniqueness_of :full_name
  validates_numericality_of :running_order

end

app/controllers/currencies_controller.rb
# CurrenciesController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class CurrenciesController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  before_filter :admin_required, :only => "destroy"
  
  def index
    # GET /currencies
    # GET /currencies.json
    @currencies = Currency.all(order: "active DESC, running_order")

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @currencies }
    end
  end

  def show
    # GET /currencies/1
    # GET /currencies/1.json
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @currency }
    end
  end

  def new
    # GET /currencies/new
    # GET /currencies/new.json
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @currency }
    end
  end

  def edit
    # GET /currencies/1/edit
    @currency = Currency.find(params[:id])
  end

  def create
    # POST /currencies
    # POST /currencies.json
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to currencies_url, notice: 'Currency was successfully created.' }
        #format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        #format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /currencies/1
    # PUT /currencies/1.json
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to currencies_url, notice: 'Currency was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /currencies/1
    # DELETE /currencies/1.json
    @currency = Currency.find(params[:id])
    if @currency.general_setting
      flash[:notice] = "Sorry, you can't delete that currency - it is the default currency for the business."
    elsif @currency.active
      flash[:notice] = "Sorry, you can't delete that currency - it is 'active'."
    else
      @currency.destroy
      flash[:notice] = "Currency deleted."
    end

    respond_to do |format|
      format.html { redirect_to currencies_url }
      #format.json { head :no_content }
    end
  end

end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="form-label"><%= f.label :iso_code, "ISO Code" %></span>
    <span class="form-field"><%= f.text_field :iso_code %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :currency_symbol %></span>
    <span class="form-field"><%= f.text_field :currency_symbol %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :full_name %></span>
    <span class="form-field"><%= f.text_field :full_name %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :running_order %></span>
    <span class="form-field"><%= f.number_field :running_order %></span>
  </div>
  <div class="field">
    <span class="form-label"><%= f.label :active %></span>
    <span class="form-field"><%= f.check_box :active %></span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Edit Currency</h1>

<%= render 'form' %>

<%= link_to 'View', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Currencies</h1>
<table>
  <tr>
    <th style="width: 100px;">ISO code</th>
    <th style="width: 100px;">Symbol</th>
    <th style="width: 200px;">Full name</th>
    <th style="width: 100px;">Running order</th>
    <th style="width: 100px;">Active</th>
  </tr>
  <% @currencies.each do |currency| %>
    <tr style="background-color: <%= cycle("inherit","inherit") %>;" class="graduated-background">
      <td><%= currency.iso_code %></td>
      <td><%= sanitize currency.currency_symbol %></td>
      <td><%= currency.full_name %></td>
      <td><%= currency.running_order %></td>
      <td><%= sanitize tick_or_cross currency.active %></td>
      <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
      <% if admin_user %>
      <%= render :partial => '/layouts/delete_button', :locals => {:label => "currency", :item => currency} -%>
      <% end %>
    </td>
  <% end %>
</table><br/>
<%= link_to 'New', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<h1>Currency #<%= params[:id] %></h1>
<table>
  <tr><td>Iso code:</td><td><%= @currency.iso_code %></td></tr>
  <tr><td>Currency symbol:</td><td><%= @currency.currency_symbol %></td></tr>
  <tr><td>Full name:</td><td><%= @currency.full_name %></td></tr>
  <tr><td>Running order:</td><td><%= @currency.running_order %></td></tr>
  <tr><td>Active:</td><td><%= sanitize tick_or_cross @currency.active %></td></tr>
</table><br/>
<%= link_to 'Back', currencies_path %> | <%= link_to 'Edit', edit_currency_path(@currency) %>